import = [
  "C:/Users/eduard.llado/AppData/Roaming/alacritty/catppuccin-frappe.toml"
]

[env]
term = "xterm-256color"

[window]
decorations = "none"
startup_mode = "Maximized"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

